plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md
  - LICENSE.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - codeingSetup_GitHubEnv.md
  - SetupGitHubDestkop.md
  - setupGitHub.md

theme: jekyll-theme-slate
