# This is a basic workflow to help you get started with Actions

name: Markdown Linter
on:
  - push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: install markdownlint-cli
      run:
        npm install -g markdownlint-cli
    - name: run markdownlint-cli
      run:
        markdownlint --help
