# This is a basic workflow to help you get started with Actions

name: Markdown Linter
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - name: markdownlint
      uses: logansquirel/action-markdownlint@v0.1
      
